[package]
name = "cliant-rs"
version = "0.1.0"
edition = "2021"
authors = ["Abba Valentine <valentinechibueze400@gmail.com>"]

[dependencies]
anyhow = "1.0.75"
colored = "2.0.0"
infer = "0.15.0"
log = "0.4.20"
rand = "0.8.5"
rayon = "1.7.0"
chrono="0.4.41"
regex="1.11.1"
tokio={version="1.45.1",features=["full"]}
tokio-utils="0.1.2"
reqwest = { version = "0.11.18", default-features = false, features = ["blocking", "json", "rustls-tls"] }
env_logger = "0.10.0"
clap = { version = "4.4.2", features = ["derive"] }
indicatif = "0.18.0"
ctrlc = "3.4.4"
exitcode = "1.1.2"
thiserror = "2.0.12"
url = "2.5.4"
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
actix-web = "4.11.0"
config = "0.15.14"
tokio-stream = "0.1.17"
bytes = "1.10.1"
async-trait = "0.1.89"
http = "1.3.1"
cookie = "0.18.1"
validator = { version = "0.20.0", features = ["derive"] }
fancy-regex = "0.16.1"
percent-encoding = "2.3.2"
