[package]
name = "cliant-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-log = "2.0.0"
chrono = "0.4.41"
clap = {version="4.5.40",features=["derive"]}
colored = "3.0.0"
colorize = "0.1.0"
infer = "0.19.0"
log = "0.4.27"
log4rs = "1.3.0"
num-bigint = "0.4.6"
rand = "0.9.1"
rayon = "1.10.0"
regex = "1.11.1"
reqwest = {version="0.12.20",features=["blocking","cookies"]}
serde = {version="1.0.219",features=["derive"]}
serde_json = {version="1.0.140"}
tokio = {version="1.45.1",features=["full"]}
tokio-utils = "0.1.2"
